// ALUU Name Checker game codes & required fields
// Auto-generated from ALUU game parameters list
export interface GameCheckerOption {
  code: string;          // ALUU API code, used in /api/check/{code}-check
  label: string;
  requiresServer: boolean;
  requiresCharname?: boolean;
  serverLabel?: string;
  userLabel?: string;
  charnameLabel?: string;
}

export const ALUU_GAMES: GameCheckerOption[] = [
  { code: "8_ball_pool", label: "8 Ball Pool", requiresServer: false, requiresCharname: false },
  { code: "afkjourney", label: "AFK Journey", requiresServer: false, requiresCharname: false },
  { code: "acecraft", label: "Acecraft", requiresServer: false, requiresCharname: false },
  { code: "aoem", label: "Age of Empire Mobile", requiresServer: true, requiresCharname: false },
  { code: "age_of_magic", label: "Age of Magic", requiresServer: false, requiresCharname: false },
  { code: "arena_breakout", label: "Arena Breakout", requiresServer: false, requiresCharname: false },
  { code: "arena_breakout_infinite", label: "Arena Breakout Infinite", requiresServer: false, requiresCharname: false },
  { code: "aove", label: "Arena of Valor Europe", requiresServer: false, requiresCharname: false },
  { code: "arknights_endfield", label: "Arknight: Endfield", requiresServer: true, requiresCharname: true },
  { code: "asphalt9", label: "Asphalt 9: Legends", requiresServer: true, requiresCharname: false },
  { code: "avakin_life", label: "Avakin Life", requiresServer: false, requiresCharname: false },
  { code: "azur_lane", label: "Azur Lane", requiresServer: true, requiresCharname: false },
  { code: "bigo", label: "Bigo Live Diamonds", requiresServer: false, requiresCharname: false },
  { code: "black_clover_m_asia", label: "Black Clover M Asia", requiresServer: false, requiresCharname: false },
  { code: "bsr_us", label: "Bleach: Soul Resonance (Americas)", requiresServer: false, requiresCharname: false },
  { code: "bsr_eu", label: "Bleach: Soul Resonance (Europe)", requiresServer: false, requiresCharname: false },
  { code: "bsr_sea", label: "Bleach: Soul Resonance (SEA)", requiresServer: false, requiresCharname: false },
  { code: "blockman_go", label: "Blockman Go", requiresServer: false, requiresCharname: false },
  { code: "bloodstrike", label: "Blood Strike", requiresServer: false, requiresCharname: false },
  { code: "bloodstrikeme", label: "Blood Strike MENA", requiresServer: false, requiresCharname: false },
  { code: "bullet_echo", label: "Bullet Echo", requiresServer: false, requiresCharname: false },
  { code: "cats", label: "CATS: Crash Arena Turbo Stars", requiresServer: false, requiresCharname: false },
  { code: "codm_sgmy", label: "Call of Duty Mobile Garena SGMY", requiresServer: false, requiresCharname: false },
  { code: "civ", label: "Civilization: Eras & Allies", requiresServer: false, requiresCharname: false },
  { code: "crossfire", label: "Crossfire: Legend", requiresServer: false, requiresCharname: false },
  { code: "crossout_mobile", label: "Crossout Mobile", requiresServer: false, requiresCharname: false },
  { code: "coa", label: "Crystal of Atlan", requiresServer: false, requiresCharname: false },
  { code: "deltaforce", label: "Delta Force", requiresServer: false, requiresCharname: false },
  { code: "destiny_rising", label: "Destiny: Rising", requiresServer: true, requiresCharname: false },
  { code: "dmc", label: "Devil May Cry: Peak of Combat", requiresServer: false, requiresCharname: false },
  { code: "dragon_nest_m_classic", label: "Dragon Nest M: Classic", requiresServer: true, requiresCharname: false },
  { code: "dragon_raja", label: "Dragon Raja", requiresServer: false, requiresCharname: false },
  { code: "dragonheir", label: "Dragonheir: Silent Gods", requiresServer: false, requiresCharname: false },
  { code: "dna", label: "Duet Night Abyss", requiresServer: true, requiresCharname: false },
  { code: "dunk_city_dynasty", label: "Dunk City Dynasty", requiresServer: true, requiresCharname: false },
  { code: "eafcmobile_kh", label: "EAFC Mobile Cambodia", requiresServer: false, requiresCharname: false },
  { code: "eafcmobile_my", label: "EAFC Mobile Malaysia", requiresServer: false, requiresCharname: false },
  { code: "eafcmobile_sg", label: "EAFC Mobile Singapore", requiresServer: false, requiresCharname: false },
  { code: "esc", label: "Echocalypse: Scarlet Covenant", requiresServer: false, requiresCharname: false },
  { code: "eggy_party", label: "Eggy Party", requiresServer: false, requiresCharname: false },
  { code: "enhypen_world", label: "Enhypen World", requiresServer: false, requiresCharname: false },
  { code: "etheria_restart", label: "Etheria Restart", requiresServer: true, requiresCharname: false },
  { code: "eve_echoes", label: "Eve Echoes", requiresServer: false, requiresCharname: false },
  { code: "frag", label: "FRAG Pro Shooter", requiresServer: false, requiresCharname: false },
  { code: "farlight84", label: "Farlight 84", requiresServer: false, requiresCharname: false },
  { code: "freefire_bd", label: "Freefire Bangladesh", requiresServer: false, requiresCharname: false },
  { code: "freefire_br", label: "Freefire Brazil", requiresServer: false, requiresCharname: false },
  { code: "freefire_eu", label: "Freefire Europe", requiresServer: false, requiresCharname: false },
  { code: "freefire_global", label: "Freefire Global", requiresServer: false, requiresCharname: false },
  { code: "freefire_id", label: "Freefire Indonesia", requiresServer: false, requiresCharname: false },
  { code: "freefire_latam", label: "Freefire LATAM", requiresServer: false, requiresCharname: false },
  { code: "freefire_me", label: "Freefire Middle East", requiresServer: false, requiresCharname: false },
  { code: "freefire_sg", label: "Freefire SG", requiresServer: false, requiresCharname: false },
  { code: "freefire_sgmy", label: "Freefire SGMY", requiresServer: false, requiresCharname: false },
  { code: "freefire_tw", label: "Freefire Taiwan", requiresServer: false, requiresCharname: false },
  { code: "freefire_vn", label: "Freefire Vietnam", requiresServer: false, requiresCharname: false },
  { code: "nikke", label: "GOV: Nikke", requiresServer: true, requiresCharname: false },
  { code: "garena_deltaforce_my", label: "Garena Deltaforce Malaysia", requiresServer: false, requiresCharname: false },
  { code: "garena_deltaforce_sg", label: "Garena Deltaforce Singapore", requiresServer: false, requiresCharname: false },
  { code: "garena_undawn", label: "Garena Undawn", requiresServer: false, requiresCharname: false },
  { code: "genshin", label: "Genshin Impact", requiresServer: true, requiresCharname: false },
  { code: "genshin_br", label: "Genshin Impact Brazil", requiresServer: true, requiresCharname: false },
  { code: "genshin_ca", label: "Genshin Impact Canada", requiresServer: true, requiresCharname: false },
  { code: "genshin_hk", label: "Genshin Impact Hong Kong", requiresServer: true, requiresCharname: false },
  { code: "genshin_id", label: "Genshin Impact Indonesia", requiresServer: true, requiresCharname: false },
  { code: "genshin_login", label: "Genshin Impact Login Mode", requiresServer: true, requiresCharname: true },
  { code: "genshin_my", label: "Genshin Impact Malaysia", requiresServer: true, requiresCharname: false },
  { code: "genshin_mx", label: "Genshin Impact Mexico", requiresServer: true, requiresCharname: false },
  { code: "genshin_ph", label: "Genshin Impact Philippines", requiresServer: true, requiresCharname: false },
  { code: "genshin_sg", label: "Genshin Impact Singapore", requiresServer: true, requiresCharname: false },
  { code: "genshin_tw", label: "Genshin Impact Taiwan", requiresServer: true, requiresCharname: false },
  { code: "genshin_th", label: "Genshin Impact Thailand", requiresServer: true, requiresCharname: false },
  { code: "genshin_us", label: "Genshin Impact USA", requiresServer: true, requiresCharname: false },
  { code: "gsld", label: "Ghost Story Love Destiny", requiresServer: false, requiresCharname: false },
  { code: "golden_spatula", label: "Golden Spatula", requiresServer: false, requiresCharname: false },
  { code: "growtopia", label: "Growtopia", requiresServer: false, requiresCharname: false },
  { code: "haikyu_flyhigh", label: "Haikyu Fly High SEA", requiresServer: false, requiresCharname: false },
  { code: "harry_potter_magic_awakened", label: "Harry Potter: Magic Awaken", requiresServer: true, requiresCharname: false },
  { code: "hatsune_miku", label: "Hatsune Miku", requiresServer: false, requiresCharname: false },
  { code: "heartopia", label: "Heartopia", requiresServer: true, requiresCharname: false },
  { code: "hbr", label: "Heaven Burns Red", requiresServer: false, requiresCharname: false },
  { code: "hero_clash", label: "Hero Clash", requiresServer: true, requiresCharname: false },
  { code: "honkai_impact", label: "Honkai Impact 3rd", requiresServer: false, requiresCharname: false },
  { code: "honkai_star_rail", label: "Honkai Star Rail", requiresServer: true, requiresCharname: false },
  { code: "hok", label: "Honor of Kings", requiresServer: false, requiresCharname: false },
  { code: "identityv", label: "Identity V", requiresServer: true, requiresCharname: false },
  { code: "identityv_noreceipt", label: "Identity V [No Receipt]", requiresServer: true, requiresCharname: false },
  { code: "kings_choice_sea", label: "Kings Choice SEA", requiresServer: false, requiresCharname: false },
  { code: "kingshot", label: "Kingshot", requiresServer: false, requiresCharname: false },
  { code: "knivesout", label: "Knives Out", requiresServer: true, requiresCharname: false },
  { code: "kuroko_sr", label: "Kuroko Street Rivals", requiresServer: false, requiresCharname: false },
  { code: "league_of_legends_kh", label: "League of Legends Cambodia", requiresServer: false, requiresCharname: false },
  { code: "league_of_legends_ph", label: "League of Legends Philippines", requiresServer: false, requiresCharname: false },
  { code: "league_of_legends_sg", label: "League of Legends SG", requiresServer: false, requiresCharname: false },
  { code: "league_of_legends_vn", label: "League of Legends Vietnam", requiresServer: false, requiresCharname: false },
  { code: "legend_of_neverland", label: "Legend of Neverland (NAEU)", requiresServer: false, requiresCharname: false },
  { code: "legend_of_phoenix", label: "Legend of the Phoenix", requiresServer: false, requiresCharname: false },
  { code: "legends_of_runeterra_my", label: "Legends of Runeterra", requiresServer: false, requiresCharname: false },
  { code: "life_makeover", label: "Life Makeover Global", requiresServer: false, requiresCharname: false },
  { code: "lifeafter", label: "LifeAfter", requiresServer: true, requiresCharname: false },
  { code: "likee", label: "Likee", requiresServer: false, requiresCharname: false },
  { code: "lineagew", label: "Lineage W", requiresServer: true, requiresCharname: false },
  { code: "lineage2m", label: "Lineage2M", requiresServer: true, requiresCharname: false },
  { code: "love_nikki", label: "Love Nikki", requiresServer: false, requiresCharname: false },
  { code: "lds", label: "Love and Deepspace", requiresServer: true, requiresCharname: false },
  { code: "lds_login", label: "Love and Deepspace Login Mode", requiresServer: true, requiresCharname: true },
  { code: "ludus", label: "Ludus Strategy PVP", requiresServer: false, requiresCharname: false },
  { code: "magic_chest_gogo", label: "Magic Chess Gogo", requiresServer: true, requiresCharname: false },
  { code: "mcgg_my", label: "Magic Chess Gogo Malaysia", requiresServer: true, requiresCharname: false },
  { code: "mcgg_ph", label: "Magic Chess Gogo Philippines", requiresServer: true, requiresCharname: false },
  { code: "mcgg_ru", label: "Magic Chess Gogo Russia", requiresServer: true, requiresCharname: false },
  { code: "maplestorym", label: "MapleStory M", requiresServer: true, requiresCharname: true },
  { code: "marvel_duel", label: "Marvel Duel", requiresServer: false, requiresCharname: false },
  { code: "mystic_mayhem", label: "Marvel Mystic Mayhem", requiresServer: false, requiresCharname: false },
  { code: "marvelrivals", label: "Marvel Rivals", requiresServer: false, requiresCharname: false },
  { code: "mecha_break", label: "Mecha Break", requiresServer: true, requiresCharname: false },
  { code: "metal_slug", label: "Metal Slug Awakening", requiresServer: false, requiresCharname: false },
  { code: "mla", label: "Mobile Legends Adventure", requiresServer: true, requiresCharname: false },
  { code: "mlbb_br", label: "Mobile Legends Brazil", requiresServer: true, requiresCharname: false },
  { code: "mlbb_special", label: "Mobile Legends GLOBAL", requiresServer: true, requiresCharname: false },
  { code: "mlbb", label: "Mobile Legends INDIA", requiresServer: true, requiresCharname: false },
  { code: "mlbb_exclusive", label: "Mobile Legends INDIA/PHP", requiresServer: true, requiresCharname: false },
  { code: "mlbb_global", label: "Mobile Legends INDO", requiresServer: true, requiresCharname: false },
  { code: "mlbb_ru", label: "Mobile Legends Russia", requiresServer: true, requiresCharname: false },
  { code: "mlbb_tr", label: "Mobile Legends Turkey", requiresServer: true, requiresCharname: false },
  { code: "mso", label: "Modern Strike Online", requiresServer: false, requiresCharname: false },
  { code: "mongil_star_dive", label: "Mongil Star Dive", requiresServer: true, requiresCharname: false },
  { code: "moonlight_blade_m", label: "Moonlight Blade M", requiresServer: false, requiresCharname: false },
  { code: "my_singing_monsters", label: "My Singing Monsters", requiresServer: false, requiresCharname: false },
  { code: "neo_artifacts", label: "Neo Artifacts", requiresServer: false, requiresCharname: false },
  { code: "nte", label: "Neverness to Everness", requiresServer: true, requiresCharname: true },
  { code: "oncehuman", label: "Once Human", requiresServer: true, requiresCharname: true },
  { code: "onmyoji_arena", label: "Onmyoji Arena", requiresServer: false, requiresCharname: false },
  { code: "overmortal_idle", label: "Overmortal Idle", requiresServer: false, requiresCharname: false },
  { code: "overmortal_idle_sea", label: "Overmortal Idle SEA", requiresServer: false, requiresCharname: false },
  { code: "oxide", label: "Oxide: Survival Island", requiresServer: false, requiresCharname: false },
  { code: "pubgm", label: "PUBG Mobile", requiresServer: false, requiresCharname: false },
  { code: "ptn", label: "Path to Nowhere", requiresServer: false, requiresCharname: false },
  { code: "pixel_gun_3d", label: "Pixel Gun 3D", requiresServer: false, requiresCharname: false },
  { code: "poppolive", label: "Poppo Live", requiresServer: false, requiresCharname: false },
  { code: "project_entropy", label: "Project Entropy", requiresServer: false, requiresCharname: false },
  { code: "pgr", label: "Punishing Gray Raven", requiresServer: true, requiresCharname: false },
  { code: "puzzles_and_survival", label: "Puzzles and Survival", requiresServer: true, requiresCharname: true },
  { code: "racing_master_latam", label: "Racing Master LATAM", requiresServer: false, requiresCharname: false },
  { code: "racing_master_na", label: "Racing Master NA", requiresServer: false, requiresCharname: false },
  { code: "racing_master_sea", label: "Racing Master SEA", requiresServer: false, requiresCharname: false },
  { code: "ragnarok_crush", label: "Ragnarok Crush", requiresServer: false, requiresCharname: false },
  { code: "ragnarok_idle", label: "Ragnarok Idle Adventure Plus", requiresServer: true, requiresCharname: true },
  { code: "ragnarok_origin", label: "Ragnarok Origin", requiresServer: true, requiresCharname: true },
  { code: "ragnarok_x", label: "Ragnarok X", requiresServer: false, requiresCharname: false },
  { code: "rsm", label: "Rainbow Six Mobile", requiresServer: false, requiresCharname: false },
  { code: "rsm_sg", label: "Rainbow Six Mobile Singapore", requiresServer: false, requiresCharname: false },
  { code: "rememento", label: "Rememento: White Shadows", requiresServer: false, requiresCharname: false },
  { code: "sausage_man", label: "Sausage Man", requiresServer: false, requiresCharname: false },
  { code: "sea_of_conquest", label: "Sea of Conquest", requiresServer: false, requiresCharname: false },
  { code: "shining_nikki", label: "Shining Nikki", requiresServer: false, requiresCharname: false },
  { code: "sab", label: "Silver and Blood", requiresServer: true, requiresCharname: false },
  { code: "sky_cotl", label: "Sky Children of the Light", requiresServer: false, requiresCharname: false },
  { code: "scz", label: "Snowbreak Containment Zone", requiresServer: true, requiresCharname: false },
  { code: "solo_leveling", label: "Solo Leveling: Arise", requiresServer: true, requiresCharname: false },
  { code: "slnw", label: "Soul Land New World", requiresServer: false, requiresCharname: false },
  { code: "spring_valley", label: "Spring Valley: Farm Adventures", requiresServer: false, requiresCharname: false },
  { code: "star_resonance", label: "Star Resonance", requiresServer: false, requiresCharname: false },
  { code: "starmaker", label: "Starmaker", requiresServer: false, requiresCharname: false },
  { code: "state_of_survival", label: "State of Survival", requiresServer: false, requiresCharname: false },
  { code: "stella_sora", label: "Stella Sora", requiresServer: false, requiresCharname: false },
  { code: "stormshot", label: "Stormshot", requiresServer: false, requiresCharname: false },
  { code: "stumble_guys", label: "Stumble Guys", requiresServer: false, requiresCharname: false },
  { code: "super_sus", label: "Super Sus", requiresServer: false, requiresCharname: false },
  { code: "swordofjustice", label: "Sword of Justice", requiresServer: true, requiresCharname: false },
  { code: "swordofjustice_eu", label: "Sword of Justice Europe", requiresServer: true, requiresCharname: false },
  { code: "swordofjustice_us", label: "Sword of Justice North America", requiresServer: true, requiresCharname: false },
  { code: "t3_arena", label: "T3 Arena", requiresServer: false, requiresCharname: false },
  { code: "teamfight_tactics_id", label: "Teamfight Tactics Indonesia", requiresServer: false, requiresCharname: false },
  { code: "teamfight_tactics_ph", label: "Teamfight Tactics Philippines", requiresServer: false, requiresCharname: false },
  { code: "teamfight_tactics_sg", label: "Teamfight Tactics SG", requiresServer: false, requiresCharname: false },
  { code: "teamfight_tactics_th", label: "Teamfight Tactics Thailand", requiresServer: false, requiresCharname: false },
  { code: "teen_patti_gold", label: "Teen Patti Gold", requiresServer: false, requiresCharname: false },
  { code: "telegram", label: "Telegram", requiresServer: false, requiresCharname: false },
  { code: "tdr", label: "The Division Resurgence", requiresServer: false, requiresCharname: false },
  { code: "tiles_survive", label: "Tiles Survive!", requiresServer: false, requiresCharname: false },
  { code: "tomb_busters", label: "Tomb Busters", requiresServer: false, requiresCharname: false },
  { code: "tof", label: "Tower of Fantasty", requiresServer: true, requiresCharname: true },
  { code: "undawn_global", label: "Undawn Global", requiresServer: true, requiresCharname: false },
  { code: "valorant_kh", label: "Valorant Cambodia", requiresServer: false, requiresCharname: false },
  { code: "valorant_id", label: "Valorant Indonesia", requiresServer: false, requiresCharname: false },
  { code: "valorant_my", label: "Valorant Malaysia", requiresServer: false, requiresCharname: false },
  { code: "valorant_ph", label: "Valorant Philippines", requiresServer: false, requiresCharname: false },
  { code: "valorant_sg", label: "Valorant SG", requiresServer: false, requiresCharname: false },
  { code: "valorant_th", label: "Valorant Thailand", requiresServer: false, requiresCharname: false },
  { code: "valorant_vn", label: "Valorant Vietnam", requiresServer: false, requiresCharname: false },
  { code: "wor", label: "Watcher of Realms", requiresServer: true, requiresCharname: false },
  { code: "wwm", label: "Where Winds Meet", requiresServer: false, requiresCharname: false },
  { code: "whiteout_survival", label: "Whiteout Survival", requiresServer: false, requiresCharname: false },
  { code: "wild_rift_kh", label: "Wild Rift Cambodia", requiresServer: false, requiresCharname: false },
  { code: "wild_rift_ph", label: "Wild Rift Philippines", requiresServer: false, requiresCharname: false },
  { code: "wild_rift_sg", label: "Wild Rift Singapore", requiresServer: false, requiresCharname: false },
  { code: "wild_rift_vn", label: "Wild Rift Vietnam", requiresServer: false, requiresCharname: false },
  { code: "wuwa", label: "Wuthering Waves", requiresServer: true, requiresCharname: false },
  { code: "yalla_ludo", label: "Yalla Ludo", requiresServer: false, requiresCharname: false },
  { code: "zzz", label: "Zenless Zone Zero", requiresServer: true, requiresCharname: false },
  { code: "zepeto", label: "Zepeto", requiresServer: false, requiresCharname: false },
];

// Map product slug → ALUU name checker game code
const SLUG_MAP: Record<string, string> = {
  mlbb: "mlbb",
  "mlbb-large": "mlbb",
  "mlbb-mid": "mlbb",
  "mlbb-diamond-recharge": "mlbb",
  mlbb_global: "mlbb_global",
  "mlbb-global": "mlbb_global",
  "mlbb-brazil": "mlbb_br",
  "magic-chess-gogo": "magic_chest_gogo",
  "magic-chess": "magic_chest_gogo",
  pubgm: "pubgm",
  pubg: "pubgm",
  bgmi: "pubgm",
  freefire: "freefire_global",
  "free-fire": "freefire_global",
  "freefire-max": "freefire_global",
  hok: "hok",
  "honor-of-kings": "hok",
  genshin: "genshin",
  "genshin-impact": "genshin",
  wuwa: "wuwa",
  "wuthering-waves": "wuwa",
  "honkai-star-rail": "honkai_star_rail",
  "zenless-zone-zero": "zzz",
};

export function getGameCodeForSlug(slug?: string | null): string | null {
  if (!slug) return null;
  const s = slug.toLowerCase();
  if (SLUG_MAP[s]) return SLUG_MAP[s];
  // Fuzzy fallback
  if (s.startsWith("mlbb")) return "mlbb";
  if (s.includes("magic-chess") || s.includes("magic_chess")) return "magic_chest_gogo";
  if (s.includes("pubg") || s.includes("bgmi")) return "pubgm";
  if (s.includes("free-fire") || s.includes("freefire")) return "freefire_global";
  if (s.includes("genshin")) return "genshin";
  if (s.includes("honor") && s.includes("king")) return "hok";
  if (s.includes("wuther")) return "wuwa";
  // Direct code match (game code used as slug)
  const direct = ALUU_GAMES.find(g => g.code === s);
  if (direct) return direct.code;
  return null;
}

export function getGameByCode(code?: string | null): GameCheckerOption | null {
  if (!code) return null;
  return ALUU_GAMES.find(g => g.code === code) || null;
}
